---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = ".",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mrgsim.ds

<!-- badges: start -->
<!-- badges: end -->

About mrgsim.ds - 


## Installation

You can install the development version of mrgsim.ds from 
[GitHub](https://github.com/kylebaron/mrgsim.ds) with:

``` r
# install.packages("devtools")
devtools::install_github("kylebaron/mrgsim.ds")
```

## Example 

We will illustrate mrgsim.ds by doing a simulation. 

```{r, message = FALSE}
library(mrgsim.ds)

mod <- modlib_ds("1005", Req = "IPRED")

data <- expand.ev(amt = 100, ID = 1:1000)
```

mrgsim.ds provides a new `mrgsim()` variant - `mrgsim_ds()`:

```{r}
out <- mrgsim_ds(mod, data)

out
```

The output object doesn't actually carry the simulated data, but
rather a pointer to the data in parquet files on your disk.


```{r}
as_arrow_ds(out)
```



```{r}
plot(out)
```

